### ISSUE TITLE
FIXX ITT 1.7 NOT WORKING

### ISSUE THREAD

**Issue by GxZGhost** [bwmsdroid/exitlag-hwid-bypass#14] opened 2021-05-01 13:53 UTC
THIS ISNT WORKING THIS FAKEEE DO NEW ONE

**Comment by GxZGhost** [comment] 2021-05-01 13:53
fastt FIXX ITTTT

**Comment by bwmsdroid** [comment] 2021-05-01 14:35
hey,
why don't you read the other issues?
dupe of #4

**Closed by bwmsdroid** 2021-05-01 14:35 UTC
